
// Generated by Cadence Genus(TM) Synthesis Solution 20.10-p001_1
// Generated on: Dec 26 2023 14:01:55 IST (Dec 26 2023 08:31:55 UTC)

// Verification Directory fv/multiplier 

module multiplier(a, b, clk, rst, product);
  input [7:0] a, b;
  input clk, rst;
  output [15:0] product;
  wire [7:0] a, b;
  wire clk, rst;
  wire [15:0] product;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire mul_13_19_n_0, mul_13_19_n_1, mul_13_19_n_2, mul_13_19_n_3,
       mul_13_19_n_4, mul_13_19_n_5, mul_13_19_n_6, mul_13_19_n_7;
  wire mul_13_19_n_8, mul_13_19_n_9, mul_13_19_n_10, mul_13_19_n_11,
       mul_13_19_n_12, mul_13_19_n_13, mul_13_19_n_14, mul_13_19_n_15;
  wire mul_13_19_n_16, mul_13_19_n_17, mul_13_19_n_18, mul_13_19_n_19,
       mul_13_19_n_20, mul_13_19_n_21, mul_13_19_n_22, mul_13_19_n_23;
  wire mul_13_19_n_24, mul_13_19_n_25, mul_13_19_n_26, mul_13_19_n_27,
       mul_13_19_n_28, mul_13_19_n_29, mul_13_19_n_30, mul_13_19_n_31;
  wire mul_13_19_n_32, mul_13_19_n_33, mul_13_19_n_34, mul_13_19_n_35,
       mul_13_19_n_36, mul_13_19_n_37, mul_13_19_n_38, mul_13_19_n_39;
  wire mul_13_19_n_40, mul_13_19_n_41, mul_13_19_n_42, mul_13_19_n_43,
       mul_13_19_n_44, mul_13_19_n_45, mul_13_19_n_46, mul_13_19_n_47;
  wire mul_13_19_n_48, mul_13_19_n_50, mul_13_19_n_51, mul_13_19_n_52,
       mul_13_19_n_53, mul_13_19_n_54, mul_13_19_n_55, mul_13_19_n_56;
  wire mul_13_19_n_57, mul_13_19_n_58, mul_13_19_n_59, mul_13_19_n_60,
       mul_13_19_n_61, mul_13_19_n_62, mul_13_19_n_63, mul_13_19_n_64;
  wire mul_13_19_n_65, mul_13_19_n_66, mul_13_19_n_67, mul_13_19_n_68,
       mul_13_19_n_69, mul_13_19_n_70, mul_13_19_n_71, mul_13_19_n_72;
  wire mul_13_19_n_73, mul_13_19_n_74, mul_13_19_n_75, mul_13_19_n_76,
       mul_13_19_n_78, mul_13_19_n_79, mul_13_19_n_80, mul_13_19_n_81;
  wire mul_13_19_n_82, mul_13_19_n_83, mul_13_19_n_84, mul_13_19_n_85,
       mul_13_19_n_86, mul_13_19_n_87, mul_13_19_n_88, mul_13_19_n_89;
  wire mul_13_19_n_90, mul_13_19_n_91, mul_13_19_n_92, mul_13_19_n_93,
       mul_13_19_n_94, mul_13_19_n_95, mul_13_19_n_96, mul_13_19_n_97;
  wire mul_13_19_n_98, mul_13_19_n_99, mul_13_19_n_100,
       mul_13_19_n_101, mul_13_19_n_102, mul_13_19_n_103,
       mul_13_19_n_104, mul_13_19_n_105;
  wire mul_13_19_n_106, mul_13_19_n_107, mul_13_19_n_108,
       mul_13_19_n_109, mul_13_19_n_110, mul_13_19_n_111,
       mul_13_19_n_112, mul_13_19_n_113;
  wire mul_13_19_n_114, mul_13_19_n_115, mul_13_19_n_116,
       mul_13_19_n_117, mul_13_19_n_118, mul_13_19_n_119,
       mul_13_19_n_120, mul_13_19_n_121;
  wire mul_13_19_n_122, mul_13_19_n_123, mul_13_19_n_124,
       mul_13_19_n_125, mul_13_19_n_126, mul_13_19_n_127,
       mul_13_19_n_128, mul_13_19_n_129;
  wire mul_13_19_n_130, mul_13_19_n_131, mul_13_19_n_132,
       mul_13_19_n_133, mul_13_19_n_134, mul_13_19_n_135,
       mul_13_19_n_136, mul_13_19_n_137;
  wire mul_13_19_n_138, mul_13_19_n_139, mul_13_19_n_140,
       mul_13_19_n_141, mul_13_19_n_142, mul_13_19_n_143,
       mul_13_19_n_144, mul_13_19_n_145;
  wire mul_13_19_n_146, mul_13_19_n_147, mul_13_19_n_148,
       mul_13_19_n_149, mul_13_19_n_150, mul_13_19_n_151,
       mul_13_19_n_152, mul_13_19_n_153;
  wire mul_13_19_n_154, mul_13_19_n_155, mul_13_19_n_156,
       mul_13_19_n_157, mul_13_19_n_158, mul_13_19_n_159,
       mul_13_19_n_160, mul_13_19_n_161;
  wire n_0, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33;
  DFFR_X1 \product_reg[15] (.RN (n_0), .CK (clk), .D (n_18), .Q
       (product[15]), .QN (UNCONNECTED));
  DFFR_X1 \product_reg[14] (.RN (n_0), .CK (clk), .D (n_19), .Q
       (product[14]), .QN (UNCONNECTED0));
  DFFR_X1 \product_reg[12] (.RN (n_0), .CK (clk), .D (n_21), .Q
       (product[12]), .QN (UNCONNECTED1));
  DFFR_X1 \product_reg[8] (.RN (n_0), .CK (clk), .D (n_25), .Q
       (product[8]), .QN (UNCONNECTED2));
  DFFR_X1 \product_reg[0] (.RN (n_0), .CK (clk), .D (n_33), .Q
       (product[0]), .QN (UNCONNECTED3));
  DFFR_X1 \product_reg[7] (.RN (n_0), .CK (clk), .D (n_26), .Q
       (product[7]), .QN (UNCONNECTED4));
  DFFR_X1 \product_reg[11] (.RN (n_0), .CK (clk), .D (n_22), .Q
       (product[11]), .QN (UNCONNECTED5));
  DFFR_X1 \product_reg[6] (.RN (n_0), .CK (clk), .D (n_27), .Q
       (product[6]), .QN (UNCONNECTED6));
  DFFR_X1 \product_reg[5] (.RN (n_0), .CK (clk), .D (n_28), .Q
       (product[5]), .QN (UNCONNECTED7));
  DFFR_X1 \product_reg[13] (.RN (n_0), .CK (clk), .D (n_20), .Q
       (product[13]), .QN (UNCONNECTED8));
  DFFR_X1 \product_reg[10] (.RN (n_0), .CK (clk), .D (n_23), .Q
       (product[10]), .QN (UNCONNECTED9));
  DFFR_X1 \product_reg[4] (.RN (n_0), .CK (clk), .D (n_29), .Q
       (product[4]), .QN (UNCONNECTED10));
  DFFR_X1 \product_reg[3] (.RN (n_0), .CK (clk), .D (n_30), .Q
       (product[3]), .QN (UNCONNECTED11));
  DFFR_X1 \product_reg[9] (.RN (n_0), .CK (clk), .D (n_24), .Q
       (product[9]), .QN (UNCONNECTED12));
  DFFR_X1 \product_reg[2] (.RN (n_0), .CK (clk), .D (n_31), .Q
       (product[2]), .QN (UNCONNECTED13));
  DFFR_X1 \product_reg[1] (.RN (n_0), .CK (clk), .D (n_32), .Q
       (product[1]), .QN (UNCONNECTED14));
  INV_X1 g24(.A (rst), .ZN (n_0));
  FA_X1 mul_13_19_cdnfadd2(.A (mul_13_19_n_8), .B (mul_13_19_n_76), .CI
       (mul_13_19_n_70), .CO (mul_13_19_n_91), .S (n_31));
  FA_X1 mul_13_19_cdnfadd3(.A (mul_13_19_n_65), .B (mul_13_19_n_140),
       .CI (mul_13_19_n_91), .CO (mul_13_19_n_90), .S (n_30));
  FA_X1 mul_13_19_cdnfadd4(.A (mul_13_19_n_152), .B (mul_13_19_n_141),
       .CI (mul_13_19_n_90), .CO (mul_13_19_n_89), .S (n_29));
  FA_X1 mul_13_19_cdnfadd5(.A (mul_13_19_n_153), .B (mul_13_19_n_142),
       .CI (mul_13_19_n_89), .CO (mul_13_19_n_88), .S (n_28));
  FA_X1 mul_13_19_cdnfadd6(.A (mul_13_19_n_154), .B (mul_13_19_n_143),
       .CI (mul_13_19_n_88), .CO (mul_13_19_n_87), .S (n_27));
  FA_X1 mul_13_19_cdnfadd7(.A (mul_13_19_n_155), .B (mul_13_19_n_144),
       .CI (mul_13_19_n_87), .CO (mul_13_19_n_86), .S (n_26));
  FA_X1 mul_13_19_cdnfadd8(.A (mul_13_19_n_156), .B (mul_13_19_n_145),
       .CI (mul_13_19_n_86), .CO (mul_13_19_n_85), .S (n_25));
  FA_X1 mul_13_19_cdnfadd9(.A (mul_13_19_n_157), .B (mul_13_19_n_146),
       .CI (mul_13_19_n_85), .CO (mul_13_19_n_84), .S (n_24));
  FA_X1 mul_13_19_cdnfadd10(.A (mul_13_19_n_158), .B (mul_13_19_n_147),
       .CI (mul_13_19_n_84), .CO (mul_13_19_n_83), .S (n_23));
  FA_X1 mul_13_19_cdnfadd11(.A (mul_13_19_n_159), .B (mul_13_19_n_148),
       .CI (mul_13_19_n_83), .CO (mul_13_19_n_82), .S (n_22));
  FA_X1 mul_13_19_cdnfadd12(.A (mul_13_19_n_160), .B (mul_13_19_n_149),
       .CI (mul_13_19_n_82), .CO (mul_13_19_n_81), .S (n_21));
  FA_X1 mul_13_19_cdnfadd13(.A (mul_13_19_n_161), .B (mul_13_19_n_150),
       .CI (mul_13_19_n_81), .CO (mul_13_19_n_80), .S (n_20));
  FA_X1 mul_13_19_cdnfadd14(.A (mul_13_19_n_38), .B (mul_13_19_n_151),
       .CI (mul_13_19_n_80), .CO (n_18), .S (n_19));
  FA_X1 mul_13_19_cdnfadd_003_0(.A (mul_13_19_n_33), .B
       (mul_13_19_n_16), .CI (mul_13_19_n_72), .CO (mul_13_19_n_152),
       .S (mul_13_19_n_140));
  FA_X1 mul_13_19_cdnfadd_004_0(.A (mul_13_19_n_13), .B
       (mul_13_19_n_1), .CI (mul_13_19_n_17), .CO (mul_13_19_n_139), .S
       (mul_13_19_n_138));
  FA_X1 mul_13_19_cdnfadd_004_1(.A (mul_13_19_n_74), .B
       (mul_13_19_n_64), .CI (mul_13_19_n_138), .CO (mul_13_19_n_153),
       .S (mul_13_19_n_141));
  FA_X1 mul_13_19_cdnfadd_005_0(.A (mul_13_19_n_48), .B
       (mul_13_19_n_34), .CI (mul_13_19_n_5), .CO (mul_13_19_n_137), .S
       (mul_13_19_n_136));
  FA_X1 mul_13_19_cdnfadd_005_1(.A (mul_13_19_n_14), .B
       (mul_13_19_n_78), .CI (mul_13_19_n_68), .CO (mul_13_19_n_135),
       .S (mul_13_19_n_134));
  FA_X1 mul_13_19_cdnfadd_005_2(.A (mul_13_19_n_139), .B
       (mul_13_19_n_136), .CI (mul_13_19_n_134), .CO (mul_13_19_n_154),
       .S (mul_13_19_n_142));
  FA_X1 mul_13_19_cdnfadd_006_0(.A (mul_13_19_n_26), .B
       (mul_13_19_n_22), .CI (mul_13_19_n_20), .CO (mul_13_19_n_133),
       .S (mul_13_19_n_132));
  FA_X1 mul_13_19_cdnfadd_006_1(.A (mul_13_19_n_24), .B
       (mul_13_19_n_42), .CI (mul_13_19_n_67), .CO (mul_13_19_n_131),
       .S (mul_13_19_n_130));
  FA_X1 mul_13_19_cdnfadd_006_2(.A (mul_13_19_n_75), .B
       (mul_13_19_n_137), .CI (mul_13_19_n_132), .CO (mul_13_19_n_111),
       .S (mul_13_19_n_110));
  FA_X1 mul_13_19_cdnfadd_006_3(.A (mul_13_19_n_135), .B
       (mul_13_19_n_130), .CI (mul_13_19_n_110), .CO (mul_13_19_n_155),
       .S (mul_13_19_n_143));
  FA_X1 mul_13_19_cdnfadd_007_0(.A (mul_13_19_n_21), .B
       (mul_13_19_n_43), .CI (mul_13_19_n_46), .CO (mul_13_19_n_129),
       .S (mul_13_19_n_128));
  FA_X1 mul_13_19_cdnfadd_007_1(.A (mul_13_19_n_52), .B
       (mul_13_19_n_25), .CI (mul_13_19_n_35), .CO (mul_13_19_n_127),
       .S (mul_13_19_n_126));
  FA_X1 mul_13_19_cdnfadd_007_2(.A (mul_13_19_n_69), .B
       (mul_13_19_n_73), .CI (mul_13_19_n_133), .CO (mul_13_19_n_109),
       .S (mul_13_19_n_108));
  FA_X1 mul_13_19_cdnfadd_007_3(.A (mul_13_19_n_126), .B
       (mul_13_19_n_128), .CI (mul_13_19_n_131), .CO (mul_13_19_n_107),
       .S (mul_13_19_n_106));
  FA_X1 mul_13_19_cdnfadd_007_4(.A (mul_13_19_n_108), .B
       (mul_13_19_n_111), .CI (mul_13_19_n_106), .CO (mul_13_19_n_156),
       .S (mul_13_19_n_144));
  FA_X1 mul_13_19_cdnfadd_008_0(.A (mul_13_19_n_39), .B
       (mul_13_19_n_45), .CI (mul_13_19_n_2), .CO (mul_13_19_n_125), .S
       (mul_13_19_n_124));
  FA_X1 mul_13_19_cdnfadd_008_1(.A (mul_13_19_n_12), .B
       (mul_13_19_n_11), .CI (mul_13_19_n_79), .CO (mul_13_19_n_123),
       .S (mul_13_19_n_122));
  FA_X1 mul_13_19_cdnfadd_008_2(.A (mul_13_19_n_66), .B
       (mul_13_19_n_129), .CI (mul_13_19_n_127), .CO (mul_13_19_n_105),
       .S (mul_13_19_n_104));
  FA_X1 mul_13_19_cdnfadd_008_3(.A (mul_13_19_n_124), .B
       (mul_13_19_n_122), .CI (mul_13_19_n_109), .CO (mul_13_19_n_97),
       .S (mul_13_19_n_96));
  FA_X1 mul_13_19_cdnfadd_008_4(.A (mul_13_19_n_104), .B
       (mul_13_19_n_107), .CI (mul_13_19_n_96), .CO (mul_13_19_n_157),
       .S (mul_13_19_n_145));
  FA_X1 mul_13_19_cdnfadd_009_0(.A (mul_13_19_n_7), .B
       (mul_13_19_n_23), .CI (mul_13_19_n_51), .CO (mul_13_19_n_121),
       .S (mul_13_19_n_120));
  FA_X1 mul_13_19_cdnfadd_009_1(.A (mul_13_19_n_41), .B
       (mul_13_19_n_19), .CI (mul_13_19_n_9), .CO (mul_13_19_n_119), .S
       (mul_13_19_n_118));
  FA_X1 mul_13_19_cdnfadd_009_2(.A (mul_13_19_n_71), .B
       (mul_13_19_n_125), .CI (mul_13_19_n_118), .CO (mul_13_19_n_103),
       .S (mul_13_19_n_102));
  FA_X1 mul_13_19_cdnfadd_009_3(.A (mul_13_19_n_120), .B
       (mul_13_19_n_123), .CI (mul_13_19_n_105), .CO (mul_13_19_n_95),
       .S (mul_13_19_n_94));
  FA_X1 mul_13_19_cdnfadd_009_4(.A (mul_13_19_n_102), .B
       (mul_13_19_n_94), .CI (mul_13_19_n_97), .CO (mul_13_19_n_158),
       .S (mul_13_19_n_146));
  FA_X1 mul_13_19_cdnfadd_010_0(.A (mul_13_19_n_6), .B (mul_13_19_n_3),
       .CI (mul_13_19_n_47), .CO (mul_13_19_n_117), .S
       (mul_13_19_n_116));
  FA_X1 mul_13_19_cdnfadd_010_1(.A (mul_13_19_n_18), .B
       (mul_13_19_n_37), .CI (mul_13_19_n_119), .CO (mul_13_19_n_101),
       .S (mul_13_19_n_100));
  FA_X1 mul_13_19_cdnfadd_010_2(.A (mul_13_19_n_121), .B
       (mul_13_19_n_116), .CI (mul_13_19_n_100), .CO (mul_13_19_n_93),
       .S (mul_13_19_n_92));
  FA_X1 mul_13_19_cdnfadd_010_3(.A (mul_13_19_n_103), .B
       (mul_13_19_n_92), .CI (mul_13_19_n_95), .CO (mul_13_19_n_159),
       .S (mul_13_19_n_147));
  FA_X1 mul_13_19_cdnfadd_011_0(.A (mul_13_19_n_0), .B
       (mul_13_19_n_50), .CI (mul_13_19_n_44), .CO (mul_13_19_n_115),
       .S (mul_13_19_n_114));
  FA_X1 mul_13_19_cdnfadd_011_1(.A (mul_13_19_n_40), .B
       (mul_13_19_n_117), .CI (mul_13_19_n_114), .CO (mul_13_19_n_99),
       .S (mul_13_19_n_98));
  FA_X1 mul_13_19_cdnfadd_011_2(.A (mul_13_19_n_101), .B
       (mul_13_19_n_98), .CI (mul_13_19_n_93), .CO (mul_13_19_n_149),
       .S (mul_13_19_n_148));
  FA_X1 mul_13_19_cdnfadd_012_0(.A (mul_13_19_n_15), .B
       (mul_13_19_n_32), .CI (mul_13_19_n_36), .CO (mul_13_19_n_113),
       .S (mul_13_19_n_112));
  FA_X1 mul_13_19_cdnfadd_012_1(.A (mul_13_19_n_115), .B
       (mul_13_19_n_112), .CI (mul_13_19_n_99), .CO (mul_13_19_n_150),
       .S (mul_13_19_n_160));
  FA_X1 mul_13_19_cdnfadd_013_0(.A (mul_13_19_n_4), .B
       (mul_13_19_n_10), .CI (mul_13_19_n_113), .CO (mul_13_19_n_151),
       .S (mul_13_19_n_161));
  AOI21_X1 mul_13_19_g410(.A (mul_13_19_n_71), .B1 (mul_13_19_n_27),
       .B2 (mul_13_19_n_59), .ZN (mul_13_19_n_79));
  AOI21_X1 mul_13_19_g411(.A (mul_13_19_n_67), .B1 (mul_13_19_n_62),
       .B2 (mul_13_19_n_61), .ZN (mul_13_19_n_78));
  AOI21_X1 mul_13_19_g412(.A (mul_13_19_n_70), .B1 (mul_13_19_n_30),
       .B2 (mul_13_19_n_29), .ZN (n_32));
  AOI21_X1 mul_13_19_g413(.A (mul_13_19_n_65), .B1 (mul_13_19_n_53),
       .B2 (mul_13_19_n_54), .ZN (mul_13_19_n_76));
  AOI21_X1 mul_13_19_g414(.A (mul_13_19_n_69), .B1 (mul_13_19_n_60),
       .B2 (mul_13_19_n_57), .ZN (mul_13_19_n_75));
  AOI21_X1 mul_13_19_g415(.A (mul_13_19_n_68), .B1 (mul_13_19_n_28),
       .B2 (mul_13_19_n_31), .ZN (mul_13_19_n_74));
  AOI21_X1 mul_13_19_g416(.A (mul_13_19_n_66), .B1 (mul_13_19_n_58),
       .B2 (mul_13_19_n_55), .ZN (mul_13_19_n_73));
  AOI21_X1 mul_13_19_g417(.A (mul_13_19_n_64), .B1 (mul_13_19_n_63),
       .B2 (mul_13_19_n_56), .ZN (mul_13_19_n_72));
  NOR2_X1 mul_13_19_g418(.A1 (mul_13_19_n_59), .A2 (mul_13_19_n_27),
       .ZN (mul_13_19_n_71));
  NOR2_X1 mul_13_19_g419(.A1 (mul_13_19_n_29), .A2 (mul_13_19_n_30),
       .ZN (mul_13_19_n_70));
  NOR2_X1 mul_13_19_g420(.A1 (mul_13_19_n_57), .A2 (mul_13_19_n_60),
       .ZN (mul_13_19_n_69));
  NOR2_X1 mul_13_19_g421(.A1 (mul_13_19_n_31), .A2 (mul_13_19_n_28),
       .ZN (mul_13_19_n_68));
  NOR2_X1 mul_13_19_g422(.A1 (mul_13_19_n_61), .A2 (mul_13_19_n_62),
       .ZN (mul_13_19_n_67));
  NOR2_X1 mul_13_19_g423(.A1 (mul_13_19_n_55), .A2 (mul_13_19_n_58),
       .ZN (mul_13_19_n_66));
  NOR2_X1 mul_13_19_g424(.A1 (mul_13_19_n_54), .A2 (mul_13_19_n_53),
       .ZN (mul_13_19_n_65));
  NOR2_X1 mul_13_19_g425(.A1 (mul_13_19_n_56), .A2 (mul_13_19_n_63),
       .ZN (mul_13_19_n_64));
  AND2_X1 mul_13_19_g426(.A1 (b[2]), .A2 (a[5]), .ZN (mul_13_19_n_52));
  AND2_X1 mul_13_19_g427(.A1 (b[5]), .A2 (a[4]), .ZN (mul_13_19_n_51));
  AND2_X1 mul_13_19_g428(.A1 (b[5]), .A2 (a[6]), .ZN (mul_13_19_n_50));
  AND2_X1 mul_13_19_g429(.A1 (b[0]), .A2 (a[0]), .ZN (n_33));
  AND2_X1 mul_13_19_g430(.A1 (b[3]), .A2 (a[2]), .ZN (mul_13_19_n_48));
  AND2_X1 mul_13_19_g431(.A1 (b[6]), .A2 (a[4]), .ZN (mul_13_19_n_47));
  AND2_X1 mul_13_19_g432(.A1 (b[4]), .A2 (a[3]), .ZN (mul_13_19_n_46));
  AND2_X1 mul_13_19_g433(.A1 (b[5]), .A2 (a[3]), .ZN (mul_13_19_n_45));
  AND2_X1 mul_13_19_g434(.A1 (b[7]), .A2 (a[4]), .ZN (mul_13_19_n_44));
  AND2_X1 mul_13_19_g435(.A1 (b[7]), .A2 (a[0]), .ZN (mul_13_19_n_43));
  AND2_X1 mul_13_19_g436(.A1 (b[6]), .A2 (a[0]), .ZN (mul_13_19_n_42));
  AND2_X1 mul_13_19_g437(.A1 (b[6]), .A2 (a[3]), .ZN (mul_13_19_n_41));
  AND2_X1 mul_13_19_g438(.A1 (b[6]), .A2 (a[5]), .ZN (mul_13_19_n_40));
  AND2_X1 mul_13_19_g439(.A1 (b[4]), .A2 (a[4]), .ZN (mul_13_19_n_39));
  AND2_X1 mul_13_19_g440(.A1 (b[7]), .A2 (a[7]), .ZN (mul_13_19_n_38));
  AND2_X1 mul_13_19_g441(.A1 (b[5]), .A2 (a[5]), .ZN (mul_13_19_n_37));
  AND2_X1 mul_13_19_g442(.A1 (b[7]), .A2 (a[5]), .ZN (mul_13_19_n_36));
  AND2_X1 mul_13_19_g443(.A1 (b[6]), .A2 (a[1]), .ZN (mul_13_19_n_35));
  AND2_X1 mul_13_19_g444(.A1 (b[4]), .A2 (a[1]), .ZN (mul_13_19_n_34));
  AND2_X1 mul_13_19_g445(.A1 (b[3]), .A2 (a[0]), .ZN (mul_13_19_n_33));
  AND2_X1 mul_13_19_g446(.A1 (b[6]), .A2 (a[6]), .ZN (mul_13_19_n_32));
  NAND2_X1 mul_13_19_g447(.A1 (a[2]), .A2 (b[1]), .ZN (mul_13_19_n_63));
  NAND2_X1 mul_13_19_g448(.A1 (a[4]), .A2 (b[1]), .ZN (mul_13_19_n_62));
  NAND2_X1 mul_13_19_g449(.A1 (a[5]), .A2 (b[0]), .ZN (mul_13_19_n_61));
  NAND2_X1 mul_13_19_g450(.A1 (a[5]), .A2 (b[1]), .ZN (mul_13_19_n_60));
  NAND2_X1 mul_13_19_g451(.A1 (a[7]), .A2 (b[1]), .ZN (mul_13_19_n_59));
  NAND2_X1 mul_13_19_g452(.A1 (a[6]), .A2 (b[1]), .ZN (mul_13_19_n_58));
  NAND2_X1 mul_13_19_g453(.A1 (a[6]), .A2 (b[0]), .ZN (mul_13_19_n_57));
  NAND2_X1 mul_13_19_g454(.A1 (a[3]), .A2 (b[0]), .ZN (mul_13_19_n_56));
  NAND2_X1 mul_13_19_g455(.A1 (a[7]), .A2 (b[0]), .ZN (mul_13_19_n_55));
  NAND2_X1 mul_13_19_g456(.A1 (a[2]), .A2 (b[0]), .ZN (mul_13_19_n_54));
  NAND2_X1 mul_13_19_g457(.A1 (a[0]), .A2 (b[2]), .ZN (mul_13_19_n_53));
  AND2_X1 mul_13_19_g458(.A1 (b[3]), .A2 (a[3]), .ZN (mul_13_19_n_26));
  AND2_X1 mul_13_19_g459(.A1 (b[5]), .A2 (a[2]), .ZN (mul_13_19_n_25));
  AND2_X1 mul_13_19_g460(.A1 (b[5]), .A2 (a[1]), .ZN (mul_13_19_n_24));
  AND2_X1 mul_13_19_g461(.A1 (b[3]), .A2 (a[6]), .ZN (mul_13_19_n_23));
  AND2_X1 mul_13_19_g462(.A1 (b[4]), .A2 (a[2]), .ZN (mul_13_19_n_22));
  AND2_X1 mul_13_19_g463(.A1 (b[3]), .A2 (a[4]), .ZN (mul_13_19_n_21));
  AND2_X1 mul_13_19_g464(.A1 (b[2]), .A2 (a[4]), .ZN (mul_13_19_n_20));
  AND2_X1 mul_13_19_g465(.A1 (b[4]), .A2 (a[5]), .ZN (mul_13_19_n_19));
  AND2_X1 mul_13_19_g466(.A1 (b[7]), .A2 (a[3]), .ZN (mul_13_19_n_18));
  AND2_X1 mul_13_19_g467(.A1 (b[2]), .A2 (a[2]), .ZN (mul_13_19_n_17));
  AND2_X1 mul_13_19_g468(.A1 (b[2]), .A2 (a[1]), .ZN (mul_13_19_n_16));
  AND2_X1 mul_13_19_g469(.A1 (b[5]), .A2 (a[7]), .ZN (mul_13_19_n_15));
  AND2_X1 mul_13_19_g470(.A1 (b[5]), .A2 (a[0]), .ZN (mul_13_19_n_14));
  AND2_X1 mul_13_19_g471(.A1 (b[3]), .A2 (a[1]), .ZN (mul_13_19_n_13));
  AND2_X1 mul_13_19_g472(.A1 (b[6]), .A2 (a[2]), .ZN (mul_13_19_n_12));
  AND2_X1 mul_13_19_g473(.A1 (b[7]), .A2 (a[1]), .ZN (mul_13_19_n_11));
  AND2_X1 mul_13_19_g474(.A1 (b[7]), .A2 (a[6]), .ZN (mul_13_19_n_10));
  AND2_X1 mul_13_19_g475(.A1 (b[7]), .A2 (a[2]), .ZN (mul_13_19_n_9));
  AND2_X1 mul_13_19_g476(.A1 (b[1]), .A2 (a[1]), .ZN (mul_13_19_n_8));
  AND2_X1 mul_13_19_g477(.A1 (b[2]), .A2 (a[7]), .ZN (mul_13_19_n_7));
  AND2_X1 mul_13_19_g478(.A1 (b[3]), .A2 (a[7]), .ZN (mul_13_19_n_6));
  AND2_X1 mul_13_19_g479(.A1 (b[2]), .A2 (a[3]), .ZN (mul_13_19_n_5));
  AND2_X1 mul_13_19_g480(.A1 (b[6]), .A2 (a[7]), .ZN (mul_13_19_n_4));
  AND2_X1 mul_13_19_g481(.A1 (b[4]), .A2 (a[6]), .ZN (mul_13_19_n_3));
  AND2_X1 mul_13_19_g482(.A1 (b[3]), .A2 (a[5]), .ZN (mul_13_19_n_2));
  AND2_X1 mul_13_19_g483(.A1 (b[4]), .A2 (a[0]), .ZN (mul_13_19_n_1));
  AND2_X1 mul_13_19_g484(.A1 (b[4]), .A2 (a[7]), .ZN (mul_13_19_n_0));
  NAND2_X1 mul_13_19_g485(.A1 (a[4]), .A2 (b[0]), .ZN (mul_13_19_n_31));
  NAND2_X1 mul_13_19_g486(.A1 (a[0]), .A2 (b[1]), .ZN (mul_13_19_n_30));
  NAND2_X1 mul_13_19_g487(.A1 (a[1]), .A2 (b[0]), .ZN (mul_13_19_n_29));
  NAND2_X1 mul_13_19_g488(.A1 (a[3]), .A2 (b[1]), .ZN (mul_13_19_n_28));
  NAND2_X1 mul_13_19_g489(.A1 (a[6]), .A2 (b[2]), .ZN (mul_13_19_n_27));
endmodule

