
// Generated by Cadence Genus(TM) Synthesis Solution 20.10-p001_1
// Generated on: Nov 23 2023 11:24:30 IST (Nov 23 2023 05:54:30 UTC)

// Verification Directory fv/fsm_1101 

module fsm_1101(x, clk, reset, y);
  input x, clk, reset;
  output y;
  wire x, clk, reset;
  wire y;
  wire [1:0] p_st;
  wire UNCONNECTED, n_0, n_1, n_2, n_4, n_5, n_6, n_7;
  wire n_8;
  DFFR_X1 \p_st_reg[0] (.RN (n_8), .CK (clk), .D (n_7), .Q (p_st[0]),
       .QN (UNCONNECTED));
  SDFFR_X1 \p_st_reg[1] (.RN (n_8), .CK (clk), .D (n_4), .SE (n_2), .SI
       (n_6), .Q (p_st[1]), .QN (n_1));
  OAI21_X1 g157(.A (n_5), .B1 (n_0), .B2 (n_6), .ZN (n_7));
  INV_X1 g159(.A (n_4), .ZN (n_5));
  AND3_X1 g158(.A1 (n_2), .A2 (p_st[0]), .A3 (p_st[1]), .ZN (y));
  AND2_X1 g161(.A1 (p_st[0]), .A2 (n_1), .ZN (n_6));
  NOR2_X1 g160(.A1 (p_st[0]), .A2 (n_1), .ZN (n_4));
  INV_X1 g164(.A (n_2), .ZN (n_0));
  INV_X1 g163(.A (reset), .ZN (n_8));
  CLKBUF_X1 g165(.A (x), .Z (n_2));
endmodule

